### ISSUE TITLE
In Linux/Unix, how do I make  Anaconda Python become my default Python

### ISSUE THREAD

**Issue by dacosta-rafael** [TeachingDataScience/data-science-course#2]

**Comment by arahuja** [comment]
This can be done by simply prepending the location of the ananconda install to the PATH environment variable

Usually Anaconda is installed in the users home dir so the following should work:

``` sh
export PATH="$HOME/anaconda/bin:$PATH"
```

You can also add this to $HOME/.bash_profile so this is setup by default (this is what Anaconda does on install if you anser 'yes' to making it your default)

**Comment by datadave** [comment]
Thanks Arun! 

Here's [a great blog post](http://natelandau.com/my-mac-osx-bash_profile/) with more on what you can do with your bash_profile.

For deeper bashing, this [wiki is a great resource.](http://mywiki.wooledge.org/BashGuide)
