### ISSUE TITLE
Favorite Data Viz

### ISSUE THREAD

**Issue by omicron-theta** [TeachingDataScience/data-science-course#4]
What's your favorite data visualization?

**Comment by jafein** [comment]
http://map.ipviking.com/

**Comment by pmadan** [comment]
http://visualization.geblogs.com/visualization/network/

**Comment by c-trl** [comment]
http://darkhorseanalytics.com/blog/wp-content/uploads/2014/05/nyBreathe.gif

**Comment by adriana-git** [comment]
http://www.theguardian.com/world/interactive/2013/apr/30/violence-guns-best-selling-video-games

**Comment by robeddy-zz** [comment]
[The Marathon Route’s Evolving Neighborhoods](http://www.nytimes.com/interactive/2011/11/05/nyregion/the-evolving-neighborhoods-along-the-marathon.html?_r=0)

**Comment by benlapidus** [comment]
http://hint.fm/wind/

**Comment by darrensmith4** [comment]
http://www.nytimes.com/interactive/2012/02/13/us/politics/2013-budget-proposal-graphic.html

**Comment by buditanzi** [comment]
http://bl.ocks.org/mbostock/4063269

**Comment by adrianbautista** [comment]
[Th_s Lan_ Is Yo_r L_nd](http://karlward.com/this/) (includes audio too)

**Comment by dacosta-rafael** [comment]
in general, content-weight infographics   . example: http://4.bp.blogspot.com/_h30udahplVk/TM-w8FaFKaI/AAAAAAAAAAg/l8ERqUnuZuA/s640/image6.png

**Comment by josephsolway** [comment]
http://www.spatialanalysis.ca/2011/global-connectivity-mapping-out-flight-routes/

Also:

http://nyctaxi.herokuapp.com/

**Comment by jeffwenzinger** [comment]
http://2.bp.blogspot.com/-YXX05oXHlWo/Th3FPHb6DFI/AAAAAAAABXQ/UwXMCSOP3o8/s1600/syn%2Brel.png

**Comment by rducic** [comment]
http://www.youtube.com/watch?v=SrZSelcIxWM

**Comment by antoinejgrant** [comment]
http://aprilzero.com

**Comment by lentzma** [comment]
https://foursquare.com/infographics/pulse

**Comment by shirin0604** [comment]
where everyone in the world is migrating: http://qz.com/192440/where-everyone-in-the-world-is-migrating-in-one-gorgeous-chart/

**Comment by stephendaimler** [comment]
mapping the internet: http://www.technologyreview.com/news/408104/mapping-the-internet/

**Comment by ghost** [comment]
http://nyctaxi.herokuapp.com

**Comment by beccaro** [comment]
http://www.aaronkoblin.com/work/flightpatterns/

**Comment by jeffwenzinger** [comment]
http://lamages.blogspot.com/2013/03/googlevis-042-with-support-for-shiny.html

**Comment by odubno** [comment]
http://www.yelp.com/wordmap/nyc/hipster
